load seeds_dataset.txt

rand('state', 2);           

data = seeds_dataset(:,1:7); %getting data from dataset
labels = seeds_dataset(:,8); %getting labels from dataset

meanData = mean(data);
stdData = std(data);
normData = (data-meanData)./(stdData);

[pcVals, pcVecs] = pca(normData);

PC = normData * pcVecs(:,1:2);

f1 = figure(1);
hold on
plot(PC(labels==1,1),PC(labels==1,2),'rx');
plot(PC(labels==2,1),PC(labels==2,2),'bo');
plot(PC(labels==3,1),PC(labels==3,2),'g+');
legend({'Class 1', 'Class 2', 'Class 3'}, 'Location', 'southeast');

saveas(f1,'f1.png')  %save the image

error1 = kmeansfun(PC,3);     %applying kmeans until centres stop moving with 3 code vectors
error2 = kmeansfun(PC,5);     %applying kmeans until centres stop moving with 5 code vectors

%comparing quantisation errors generated by both number of centres and show the suitable number of centres
if(error1 < error2)         
        n = 3;
    else
        n = 5;
end